### ISSUE TITLE
Generate realm-browser snapshot

### ISSUE THREAD

**Issue by vicfran** [josedlpozo/Galileo#20]
realm-browser plugin hasn't a snapshot yet. It's needed to genereate a snapshot for it in order to include it in the general snapshot of the library.

In order to write the snapshot, I first thought something like:

There are N Realm databases used by this app

Database _database_name_ has n tables
_table_name_ has n columns and n rows
| column_1_name || column_2_name | ...
colum_1_value colum_2_value
...

@josedlpozo what do you think

**Comment by josedlpozo** [comment]
Looks really good that snapshot! Good work @vicfran 

Whenever you have this feature done, we could upgrade to 0.1.5 :dancer:

**Comment by vicfran** [comment]
Merged in develop
